CREATE TABLE IF NOT EXISTS products
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR   NOT NULL UNIQUE,
    category_id INTEGER   NOT NULL REFERENCES categories("id") ON UPDATE CASCADE ON DELETE CASCADE,
    brand_id    INTEGER   NOT NULL REFERENCES brands("id") ON UPDATE CASCADE ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);